# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83c4ce29aa5f6dcfd3eac1d277287b1921534c19eedeb3e6b1cbd8e3f958e68a87ccb5ff23d81cb513f902a7374441489ec436e47a0de9325a59626e658f3954

test:
  secret_key_base: c67a82db417937dc9f72f1a08b6ca41393ab9cdd6ab5a2272062168f8229475275445fec0dec1b172728d41c78db6d1e39379b3c672a35127d59bd9993bd14ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
